<?php

declare(strict_types=1);

namespace Upmind\ProvisionProviders\SslCertificates\Data;

use Upmind\ProvisionBase\Provider\DataSet\Rules;

/**
 * Order status and metadata, plus the DCV instructions and any provider-generated key material.
 *
 * The result of the state-changing calls — create, reissue, renew, restartValidation — which return the
 * DCV requirement (file or DNS record) a customer must satisfy, alongside the status the parent
 * carries. getInfo returns the parent CertificateInfoResult, without these fields: the DCV
 * confirmation value is issued only on change, so a status query cannot reproduce it.
 *
 * @property-read string|null $product_code Provider product/SKU code
 * @property-read string|null $dcv_file_path URL path the validation file is served at (file method); the file name is its basename
 * @property-read string|null $dcv_file_content Content of the validation file (file method)
 * @property-read string|null $dcv_dns_record_name Name/host of the DNS record (dns method)
 * @property-read string|null $dcv_dns_record_type DNS record type; `TXT` or `CNAME` (dns method)
 * @property-read string|null $dcv_dns_record_value Value/target of the DNS record (dns method)
 * @property-read string|null $csr PEM-encoded CSR; only when generated by the provider
 * @property-read string|null $private_key PEM-encoded private key; only when generated by the provider
 */
class CertificateOrderResult extends CertificateInfoResult
{
    public static function rules(): Rules
    {
        return new Rules(array_merge(parent::rules()->raw(), [
            'product_code' => ['nullable', 'string'],
            'dcv_file_path' => ['nullable', 'string'],
            'dcv_file_content' => ['nullable', 'string'],
            'dcv_dns_record_name' => ['nullable', 'string'],
            'dcv_dns_record_type' => ['nullable', 'in:TXT,CNAME'],
            'dcv_dns_record_value' => ['nullable', 'string'],
            'csr' => ['nullable', 'string'],
            'private_key' => ['nullable', 'string'],
        ]));
    }

    /**
     * @param string|null $productCode Provider product/SKU code
     */
    public function setProductCode(?string $productCode): self
    {
        $this->setValue('product_code', $productCode);
        return $this;
    }

    /**
     * @param string|null $filePath Validation file URL path (file method)
     */
    public function setDcvFilePath(?string $filePath): self
    {
        $this->setValue('dcv_file_path', $filePath);
        return $this;
    }

    /**
     * @param string|null $fileContent Validation file content (file method)
     */
    public function setDcvFileContent(?string $fileContent): self
    {
        $this->setValue('dcv_file_content', $fileContent);
        return $this;
    }

    /**
     * @param string|null $recordName DNS record name/host (dns method)
     */
    public function setDcvDnsRecordName(?string $recordName): self
    {
        $this->setValue('dcv_dns_record_name', $recordName);
        return $this;
    }

    /**
     * @param string|null $recordType DNS record type; TXT or CNAME (dns method)
     */
    public function setDcvDnsRecordType(?string $recordType): self
    {
        $this->setValue('dcv_dns_record_type', $recordType);
        return $this;
    }

    /**
     * @param string|null $recordValue DNS record value/target (dns method)
     */
    public function setDcvDnsRecordValue(?string $recordValue): self
    {
        $this->setValue('dcv_dns_record_value', $recordValue);
        return $this;
    }

    /**
     * @param string|null $csr PEM-encoded CSR generated by the provider
     */
    public function setCsr(?string $csr): self
    {
        $this->setValue('csr', $csr);
        return $this;
    }

    /**
     * @param string|null $privateKey PEM-encoded private key generated by the provider
     */
    public function setPrivateKey(?string $privateKey): self
    {
        $this->setValue('private_key', $privateKey);
        return $this;
    }
}
